name: CI Proyecto Habitos

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:

  web:
    name: 🌐 CI Web (React Vite)
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, '') || contains(join(github.event.commits.*.modified, ','), 'web/') || github.event_name == 'pull_request'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: 📦 Instalar dependencias
        working-directory: web
        run: npm ci

      - name: 🔍 Lint
        working-directory: web
        run: npm run lint --if-present

      - name: 🏗️ Build
        working-directory: web
        run: npm run build

  mobile:
    name: 📱 CI Mobile (Flutter)
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, '') || contains(join(github.event.commits.*.modified, ','), 'mobile/') || github.event_name == 'pull_request'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          cache: true

      - name: 📦 Dependencias Flutter
        working-directory: mobile
        run: flutter pub get

      - name: 🔍 Analyze
        working-directory: mobile
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: 🏗️ Build APK Debug
        working-directory: mobile
        run: flutter build apk --debug
